Move and wrap code from membrane_ice_plugin into GenServer
membraneframework/ex_libnice pull request #1
Opened 2020-09-24 12:28 UTC by mickel8

Move code from `membrane_ice_plugin` resposible for interacting with `libnice` and wrapt it into GenServer

2020-09-30 07:56 UTC, mat-hek requested changes

2020-09-30 07:56 UTC, mat-hek commented on README.md
> +# and send them to our peer
It's a bit unclear that `sending to our peer` means just invoking `set_remote_candidate` below

2020-09-30 07:56 UTC, mat-hek commented on README.md
> +# is ready to send and receive messages.
`Receiving message...` should imho be after `:ok = ElixirLibnice.set_remote_candidate ...`

2020-09-30 07:56 UTC, mat-hek commented on README.md
> +# {:component_state_ready, stream_id, component_id} indicates that given component in given stream
```suggestion
# `{:component_state_ready, stream_id, component_id}` indicates that given component in given stream
```

2020-09-30 07:56 UTC, mat-hek commented on README.md
> +Basically this library works similarly to [libnice] except that it doesn't support some features
missing link

2020-09-30 07:56 UTC, mat-hek commented on lib/elixir_libnice.ex
> +  Important: at this moment turn servers are not supported and they will be ignored.
so remove that argument for now

2020-09-30 07:56 UTC, mat-hek commented on lib/elixir_libnice.ex
> +          port_range :: 0..65_535
use a keyword list instead of multiple arguments - it will be more readable and easier to provide defaults and add new options

2020-09-30 07:56 UTC, mat-hek commented on lib/elixir_libnice.ex
> +  Credentials has to be passed in form of `'ufrag pwd'`.
```suggestion
  Credentials have to be passed in form of `ufrag pwd`.
```

2020-09-30 07:56 UTC, mat-hek commented on lib/elixir_libnice.ex
> +  use GenServer
Why it's actually a GenServer? Couldn't it just be a set of functions?

2020-09-30 07:56 UTC, mat-hek commented on lib/elixir_libnice.ex
>  defmodule ElixirLibnice do
Hmm, what about `ExLibnice` or `ExNice?` That's a common pattern

2020-09-30 12:25 UTC, mickel8 commented on lib/elixir_libnice.ex
> +  use GenServer
As we were talking about this we need to persist cnode pid and receive some messages from it

2020-09-30 12:55 UTC, mickel8 commented on README.md
> +Basically this library works similarly to [libnice] except that it doesn't support some features
It's on the bottom :sunglasses:

2020-09-30 13:00 UTC, mickel8 commented on lib/elixir_libnice.ex
> +  Important: at this moment turn servers are not supported and they will be ignored.
I've removed it but some commented code is still present beacuse it can be helpfull in the future. Or remove whole code connected with TURN servers?

2020-09-30 13:05 UTC, mat-hek commented on lib/elixir_libnice.ex
> +  Important: at this moment turn servers are not supported and they will be ignored.
you can just do `turn_servers = []` and TODO comment

2020-09-30 13:59 UTC, mickel8 commented
Damn, I've accidentaly forced pushed :roll_eyes:

2020-09-30 14:25 UTC, mat-hek reviewed
elixir_libnice / ElixirLibnice is left in some places

2020-09-30 14:25 UTC, mat-hek commented on lib/elixir_libnice.ex
> +    turn_servers = []
add TODO

2020-10-02 12:45 UTC, mat-hek requested changes

2020-10-02 12:45 UTC, mat-hek commented on c_src/ex_libnice/native.c
>    UNIFEX_UNUSED(len);
This is no longer unused. That's why I recommend prefixing with underscores ;)

2020-10-02 12:45 UTC, mat-hek commented on c_src/ex_libnice/native.c
> -  UnifexPayload *payload = deserialize(state->env, buf);
de/serialize functions seem not to be removed

2020-10-02 12:47 UTC, mat-hek requested changes

2020-10-02 12:47 UTC, mat-hek commented on c_src/ex_libnice/native.c
> +  payload->data=(unsigned char*)buf;
you need to memcpy `buf` to `payload->data` instead

2020-10-05 12:35 UTC, mat-hek approved these changes

2020-10-05 13:42 UTC, merged