Change C node to NIF
membraneframework/ex_libnice pull request #17
Opened 2021-08-10 14:47 UTC by mickel8

Refer to #16

2021-08-12 14:01 UTC, mat-hek requested changes

2021-08-13 14:01 UTC, mickel8 commented on lib/ex_libnice.ex
> +            impl: NIF | CNode,
I am wondering about passing and reading it from config. It would be probably for flexible but I am not sure if we want to do this.

2021-08-16 08:38 UTC, mat-hek commented on lib/ex_libnice.ex
> +            impl: NIF | CNode,
That's a good idea, I'd leave that option though, and if it's not passed then default to configuration. If it's absent too, I'd default to C node.

2021-08-16 09:38 UTC, mat-hek approved these changes

2021-08-16 09:38 UTC, mat-hek commented on lib/ex_libnice.ex
>                stream_components: %{},
```suggestion
  @enforce_keys [:parent, :impl]
   defstruct @enforce_keys ++ [
              cnode: nil,
              native_state: nil,
              stream_components: %{},
              mdns_queries: %{}
              ]
```

2021-08-16 09:49 UTC, FelonEkonom commented on c_src/ex_libnice/native.c
> +  state->reply_to = *unifex_self(env, &state->reply_to);
This line will fail, if `unifex_self(env, &state->reply_to)` returns `NULL`

2021-08-17 08:37 UTC, mat-hek approved these changes

2021-08-18 11:36 UTC, FelonEkonom approved these changes

2021-08-18 11:38 UTC, merged