Add support for turn servers
membraneframework/ex_libnice pull request #7
Opened 2021-03-02 10:33 UTC by mickel8

closes #2

2021-03-08 11:40 UTC, mat-hek requested changes

2021-03-08 11:40 UTC, mat-hek commented on lib/ex_libnice.ex
> +        relay_type
- server-specific parameters could be bundled together, reducing the number of arguments and allowing to pass multiple servers at once
- allowing enum and `:all` atom for component_id would come in handy

2021-03-08 11:40 UTC, mat-hek commented on lib/ex_libnice.ex
> +  Sets TURN server. Can be called multiple times for the same component. `relay_type` can be "udp",
you can mention that servers are not overridden

2021-03-08 11:40 UTC, mat-hek commented on c_src/ex_libnice/native.spec.exs
> +       {:ok :: label, state}
does this need to return state?

2021-03-08 11:40 UTC, mat-hek commented on c_src/ex_libnice/native.spec.exs
> +spec forget_relays(state, stream_id :: unsigned, component_id :: unsigned) :: {:ok :: label, state}
as above

2021-03-08 17:59 UTC, mickel8 commented on lib/ex_libnice.ex
> +        relay_type
I have added ability to specify list of component ids. `:all` is harder because we don't store information about how many components are created.

2021-03-09 09:52 UTC, mat-hek commented on lib/ex_libnice.ex
> +        relay_type
Don't insist, but storing that shouldn't be hard

2021-03-09 10:03 UTC, mat-hek commented on lib/ex_libnice.ex
> +        """)
I'd log the `cause` too

2021-03-09 10:07 UTC, mat-hek commented on lib/ex_libnice.ex
> +  end
Let's move that clause up and add a guard `when relay_type not in [:udp, :tcp, :tls]`. This way we won't accidentally fall into this clause and return a misleading error in the future. I'd log what was passed as the relay type also.

2021-03-09 17:08 UTC, mickel8 commented on c_src/ex_libnice/native.spec.exs
> +       {:ok :: label}
`:ok :: label` results in syntax error but `:ok` is ok :+1:

2021-03-09 17:16 UTC, mat-hek commented on c_src/ex_libnice/native.spec.exs
> +       {:ok :: label}
maybe wrap it in braces `(:ok :: label)`

2021-03-09 17:28 UTC, mickel8 commented on lib/ex_libnice.ex
> +           password :: String.t(), relay_type :: :udp | :tcp | :tls}
This would simplify some function clauses but on the other hand imo it's easier for user to specify tuple than writing map with all keys

2021-03-10 09:46 UTC, mickel8 commented on lib/ex_libnice.ex
> +        """)
Actually yes

2021-03-10 10:42 UTC, mat-hek commented on lib/ex_libnice.ex
> +           password :: String.t(), relay_type :: :udp | :tcp | :tls}
That's true, but map/struct has important profits for the user also, for example, it's impossible to mistake the order of arguments, or you can provide some defaults, like the default port

2021-03-11 11:13 UTC, mat-hek approved these changes

2021-03-11 11:13 UTC, mat-hek commented on test/ex_libnice_test.exs
> +               }
you can use `%{key: value}` syntax for maps with atom keys

2021-03-11 11:23 UTC, merged